sagsystem/customers/urls.py
# InternalImports
from . import views
# End InternalImports

# DjangoImports
from django.urls import path
# End DjangoImports


app_name = 'customers'

urlpatterns = [
    path('', views.customer_list, name='customer_list'),
    path('<int:customer_id>/', views.customer_detail, name='customer_detail'),
    path('add/', views.customer_add, name='customer_add'),
    path('<int:customer_id>/edit/', views.customer_edit, name='customer_edit'),
    path('<int:customer_id>/delete/', views.customer_delete, name='customer_delete'),
    path('delete-bulk/', views.customer_delete_bulk, name='customer_delete_bulk'),
    path('add-by_xlsx/', views.customer_add_by_xlsx, name='customer_add_by_xlsx'),
    path('export/', views.customer_export, name='customer_export'),
    path('export/ready/', views.customer_export_ready, name='customer_export_ready')
]

sagsystem/sagsystem/urls.py
# DjangoImports
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
# End DjangoImports


# Urls
urlpatterns = [
    path('admin/', admin.site.urls, name='admin'),
    path('', include('mainapp.urls')),
    path('incidents/', include('incidents.urls')),
    path('tender/', include('tender.urls')),
    path('customers/', include('customers.urls')),
]
# End Urls

# StaticForDebug
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
# End StaticForDebug

sagsystem/tender/urls.py
from django.urls import path
from . import views


urlpatterns = [
    path('', views.tender_list),
    path('cfo_true/', views.tender_cfo_true),
    path('cfo_false/', views.tender_cfo_false),
    path('cfo_null/', views.tender_cfo_null),
    path('<int:tender_id>/', views.tender_detail),
    path('add/', views.tender_add),
    path('<int:tender_id>/delete/', views.tender_delete),
    path('<int:tender_id>/edit/', views.tender_edit),
    path('<int:tender_id>/participant_add/', views.participant_add),
    path('<int:tender_id>/participants/<int:participant_id>/delete/', views.participant_delete),
    path('<int:tender_id>/goods_add/', views.goods_add),
    path('<int:tender_id>/goods/<int:goods_id>/delete/', views.goods_delete),
    path('<int:tender_id>/prices_edit/', views.prices_edit),
    path('<int:tender_id>/select-winners/', views.select_winners),
    path('<int:tender_id>/select-winners/edit/', views.select_winners_edit),
    path('<int:tender_id>/delete_selected/', views.select_winners_delete),
    path('<int:tender_id>/cpo_confirm/', views.tender_cpo_confirm),
    path('<int:tender_id>/cpo_reject/', views.tender_cpo_reject),
    path('<int:tender_id>/cfo_confirm/', views.tender_cfo_confirm),
    path('<int:tender_id>/cfo_reject/', views.tender_cfo_reject),
    path('products/', views.product_list),
    path('products/category/<int:id>/', views.product_by_category),
    path('products/add/', views.product_add),
    path('products/<int:id>/delete/', views.product_delete),
    path('products/<int:id>/edit/', views.product_edit),
    path('product-category/', views.product_category_list),
    path('product-category/add/', views.product_category_add),
    path('product-category/<int:id>/delete/', views.product_category_delete),
    path('product-category/<int:id>/edit/', views.product_category_edit),
    path('providers/', views.provider_list),
    path('providers/<int:id>/', views.provider_detail),
    path('providers/add/', views.provider_add),
    path('providers/<int:id>/delete/', views.provider_delete),
    path('providers/<int:id>/edit/', views.provider_edit),
    path('organizations/', views.organization_list),
    path('organizations/add/', views.organization_add),
    path('organizations/<int:id>/delete/', views.organization_delete),
    path('organizations/<int:id>/edit/', views.organization_edit),
]

sagsystem/customers/models.py
# DjangoImports
from django.db import models
# End DjangoImports


class Customer(models.Model):
    name = models.CharField(max_length=1000, null=True, blank=True)
    phone = models.IntegerField(null=True, blank=True)
    date_of_birth = models.DateField(null=True, blank=True)
    sex = models.CharField(max_length=1, null=True, blank=True)
    address = models.CharField(max_length=1000, null=True, blank=True)
    comment = models.TextField(null=True, blank=True)
    telegram = models.CharField(max_length=200, null=True, blank=True)
    facebook = models.CharField(max_length=200, null=True, blank=True)
    instagram = models.CharField(max_length=200, null=True, blank=True)

sagsystem/customers/forms.py
# InternalImports
from . models import Customer
# End InternalImports

# DjangoImports
from django import forms
# End DjangoImports


# CustomerForm
class CustomerForm(forms.ModelForm):
    class Meta:
        model = Customer
        fields = ('name', 'phone', 'date_of_birth', 'sex', 'address', 'telegram', 'facebook', 'instagram', 'comment')
# End CustomerForm

sagsystem/customers/views.py
# InternalImports
from .models import Customer
from .forms import CustomerForm
from mainapp.views import check_access, group_list
# End InternalImports

# DjangoImports
from django.shortcuts import render, redirect, get_object_or_404, reverse
# End DjangoImports

# ExternalImports
import openpyxl
from openpyxl.styles import Font
# End ExternalImports


# CustomerViews
def customer_list(request):
    if check_access(request.user.groups.all(), 4) or check_access(request.user.groups.all(), 5):
        customers = Customer.objects.all()
        groups = group_list(request.user.groups.all())
        context = {
            'customers': customers,
            'groups': groups,
        }
        template = 'customers/customer_list.html'
        return render(request, template, context)
    else:
        return redirect('/')


def customer_detail(request, customer_id):
    if check_access(request.user.groups.all(), 4) or check_access(request.user.groups.all(), 5):
        customer = get_object_or_404(Customer, id=customer_id)
        groups = group_list(request.user.groups.all())
        context = {
            'customer': customer,
            'groups': groups,
        }
        template = 'customers/customer_detail.html'
        return render(request, template, context)
    else:
        return redirect('/')


def customer_add(request):
    if check_access(request.user.groups.all(), 4) or check_access(request.user.groups.all(), 5):
        if request.method == 'GET':
            groups = group_list(request.user.groups.all())
            context = {
                'groups': groups,
            }
            template = 'customers/customer_add.html'
            return render(request, template, context)
        elif request.method == 'POST':
            new_customer = CustomerForm(request.POST)
            if new_customer.is_valid():
                new_customer.save()
                url = '/customers/' + str(new_customer.save().id) + '/'
                return redirect(url)
    else:
        return redirect('/')


def customer_edit(request, customer_id):
    if check_access(request.user.groups.all(), 4) or check_access(request.user.groups.all(), 5):
        customer = get_object_or_404(Customer, id=customer_id)
        if request.method == 'GET':
            groups = group_list(request.user.groups.all())
            context = {
                'customer': customer,
                'groups': groups,
            }
            template = 'customers/customer_edit.html'
            return render(request, template, context)
        elif request.method == 'POST':
            edited_customer = CustomerForm(request.POST, instance=customer)
            if edited_customer.is_valid():
                edited_customer.save()
                url = '/customers/' + str(edited_customer.save().id) + '/'
                return redirect(url)
    else:
        return redirect('/')


def customer_delete(request, customer_id):
    if check_access(request.user.groups.all(), 4):
        customer = get_object_or_404(Customer, id=customer_id)
        customer.delete()
        return redirect('customers:customer_list')
    else:
        return redirect('/')


def customer_delete_bulk(request):
    if check_access(request.user.groups.all(), 4):
        customers = Customer.objects.all()
        customers.delete()
        return redirect('customers:customer_list')
    else:
        return redirect('/')


def customer_add_by_xlsx(request):
    if check_access(request.user.groups.all(), 4) or check_access(request.user.groups.all(), 5):
        if request.method == 'GET':
            groups = group_list(request.user.groups.all())
            template = 'customers/customer_add_by_xlsx.html'
            context = {
                'groups': groups,
            }
            return render(request, template, context)
        elif request.method == 'POST':
            file = request.FILES['table']
            wt = openpyxl.load_workbook(file)
            ws = wt.active
            title = True
            adding_data = {
                'name': None,
                'phone': None,
                'date_of_birth': None,
                'sex': None,
                'address': None,
                'telegram': None,
                'facebook': None,
                'instagram': None,
                'comment': None,
            }
            data = []
            for row in ws:
                if title is True:
                    title = False
                else:
                    n = 0
                    for cell in row:
                        if n == 0:
                            adding_data['name'] = cell.value
                        elif n == 1:
                            adding_data['phone'] = cell.value
                        elif n == 2:
                            adding_data['date_of_birth'] = cell.value
                        elif n == 3:
                            adding_data['sex'] = cell.value
                        elif n == 4:
                            adding_data['address'] = cell.value
                        elif n == 5:
                            adding_data['telegram'] = cell.value
                        elif n == 6:
                            adding_data['facebook'] = cell.value
                        elif n == 7:
                            adding_data['instagram'] = cell.value
                        elif n == 8:
                            adding_data['comment'] = cell.value
                        n += 1
                    data_item = Customer(name=adding_data['name'], phone=adding_data['phone'],
                                         date_of_birth=adding_data['date_of_birth'], sex=adding_data['sex'],
                                         address=adding_data['address'], telegram=adding_data['telegram'],
                                         facebook=adding_data['facebook'], instagram=adding_data['instagram'],
                                         comment=adding_data['comment'])
                    data.append(data_item)
            Customer.objects.bulk_create(data)
            return redirect('customers:customer_list')
    else:
        return redirect('/')


def customer_export(request):
    if check_access(request.user.groups.all(), 4):
        customers = Customer.objects.all()
        table = openpyxl.Workbook()
        ws = table.active
        ws.append(['ФИО', 'Номер Телефона', 'Дата Рождения', 'Пол', 'Адрес', 'Telegram', 'Facebook', 'Instagram',
                   'Comment', ])
        for row in ws:
            for cell in row:
                cell.font = Font(bold=True)
        for customer in customers:
            add_list = [str(customer.name), str(customer.phone), str(customer.date_of_birth), str(customer.sex),
                        str(customer.address), str(customer.telegram), str(customer.facebook), str(customer.instagram),
                        str(customer.comment), ]
            print(add_list)
            for item in range(len(add_list)):
                if add_list[item] == 'None':
                    add_list[item] = None
            print(add_list)
            ws.append(add_list)

        dist = 'mainapp/static/temp/export.xlsx'

        table.save(filename=dist)

        return redirect('customers:customer_export_ready')
    else:
        return redirect('/')


def customer_export_ready(request):
    if check_access(request.user.groups.all(), 4):
        template = 'customers/customer_export_ready.html'
        return render(request, template)
    else:
        return redirect('/')
# End CustomerViews

sagsystem/customers/templates/customers/customer_add.html
{% extends 'wrapper.html' %}
{% load static %}
{% block title %}Добавить клиента - Sagsystem{% endblock %}
{% block content %}
    <div class="row incidents">
        {% include 'blocks/logo.html' %}
        {% include 'blocks/title.html' %}
        {% include 'blocks/profile.html' %}
        {% include 'customers/blocks/menu.html' %}
        <div class="col-xl-9 block__wrapper tenders-new">
            <div class="block tenders-new__wrapper">
                <h1 class="tenders-new__title">Новый клиент</h1>
                <form method="POST">
                    {% csrf_token %}
                    <label for="name">ФИО</label>
                    <input required type="text" class="tenders-new__input form-control" name="name" id="name">
                    <label for="phone">Номер телефона</label>
                    <input type="number" class="tenders-new__input form-control" name="phone" id="phone">
                    <label for="date_of_birth">Дата рождения</label>
                    <input type="date" id="date_of_birth" name="date_of_birth" class="tenders-new__input form-control">
                    <div class="tenders-new__select input-group mb-3">
                        <div class="input-group-prepend">
                            <label class="input-group-text" for="sex">Пол</label>
                        </div>
                        <select class="tenders-new__input custom-select" name="sex" id="sex">
                                <option value="М">М</option>
                                <option value="Ж">Ж</option>
                        </select>
                    </div>
                    <label for="address">Адрес</label>
                    <input type="text" class="tenders-new__input form-control" name="address" id="address">
                    <label for="telegram">Telegram</label>
                    <input type="text" class="tenders-new__input form-control" name="telegram" id="telegram">
                    <label for="facebook">Facebook</label>
                    <input type="text" class="tenders-new__input form-control" name="facebook" id="facebook">
                    <label for="instagram">Instagram</label>
                    <input type="text" class="tenders-new__input form-control" name="instagram" id="instagram">
                    <label for="comment">Комментарий</label>
                    <textarea name="comment" id="comment" cols="30" rows="10" class=" form-control tenders-new__textarea"></textarea>
                    <input type="submit" class="tenders-new__button btn btn-success" value="Сохранить" id="add_product">
                    <a href="{% url 'customers:customer_list' %}" class="tenders-new__button btn btn-dark">Отмена</a>
                </form>
            </div>
        </div>
    </div>
{% endblock %}

sagsystem/customers/templates/customers/customer_add_by_xlsx.html
{% extends 'wrapper.html' %}
{% load static %}
{% block title %}Добавить клиента - Sagsystem{% endblock %}
{% block content %}
    <div class="row incidents">
        {% include 'blocks/logo.html' %}
        {% include 'blocks/title.html' %}
        {% include 'blocks/profile.html' %}
        {% include 'customers/blocks/menu.html' %}
        <div class="col-xl-9 block__wrapper tenders-new">
            <div class="block tenders-new__wrapper">
                <h1 class="tenders-new__title">Выгрузить базу</h1>
                <form method="POST" enctype="multipart/form-data">
                    {% csrf_token %}
                    <div class="mb-3">
                        <label for="table" class="form-check-label">Файл с базой (XLSX)</label>
                        <input required type="file" class="tenders-new__input form-control" name="table" id="table">
                    </div>
                    <input type="submit" class="tenders-new__button btn btn-success" value="Сохранить" id="add_product">
                    <a href="{% url 'customers:customer_list' %}" class="tenders-new__button btn btn-dark">Отмена</a>
                </form>
            </div>
        </div>
    </div>
{% endblock %}

sagsystem/customers/templates/customers/customer_detail.html
{% extends 'wrapper.html' %}
{% load static %}
{% block title %}Добавить клиента - Sagsystem{% endblock %}
{% block content %}
    <div class="row incidents">
        {% include 'blocks/logo.html' %}
        {% include 'blocks/title.html' %}
        {% include 'blocks/profile.html' %}
        {% include 'customers/blocks/menu.html' %}
        <div class="col-xl-9 block__wrapper tenders-new">
            <div class="block tenders-new__wrapper">
                <h1 class="tenders-dashboard__title">{{ customer.name }}</h1>
                <a href="{% url 'customers:customer_edit' customer.id %}" class="btn btn-warning tenders-dashboard__new-tender">Изменить</a>
                {% if 5 in groups %}
                {% else %}
                    <a href="#" class="open-modal_modal btn btn-danger tenders-dashboard__new-tender" data-modal_modal="#del_{{ customer.id }}">Удалить</a>
                {% endif %}
                <a href="{% url 'customers:customer_list' %}" class="btn btn-dark tenders-dashboard__new-tender">Назад</a>
                <div class="row">
                    <div class="col-xl-6">
                        <h5>Номер телефона</h5>
                        {% if customer.phone %}
                            <p>{{ customer.phone }}</p>
                        {% else %}
                            <p>Не указано</p>
                        {% endif %}
                        <h5>Дата рождения</h5>
                        {% if customer.date_of_birth %}
                            <p>{{ customer.date_of_birth|date:'d.m.Y' }}</p>
                        {% else %}
                            <p>Не указано</p>
                        {% endif %}
                        <h5>Пол</h5>
                        {% if customer.sex %}
                            <p>{{ customer.sex }}</p>
                        {% else %}
                            <p>Не указано</p>
                        {% endif %}
                        <h5>Адрес</h5>
                        {% if customer.address %}
                            <p>{{ customer.address }}</p>
                        {% else %}
                            <p>Не указано</p>
                        {% endif %}
                        <h5>Telegram</h5>
                        {% if customer.telegram %}
                            <p>{{ customer.telegram }}</p>
                        {% else %}
                            <p>Не указано</p>
                        {% endif %}
                        <h5>Facebook</h5>
                        {% if customer.facebook %}
                            <p>{{ customer.facebook }}</p>
                        {% else %}
                            <p>Не указано</p>
                        {% endif %}
                        <h5>Instagram</h5>
                        {% if customer.instagram %}
                            <p>{{ customer.instagram }}</p>
                        {% else %}
                            <p>Не указано</p>
                        {% endif %}
                    </div>
                    <div class="col-xl-6">
                        <h5>Комментарий</h5>
                        {% if customer.comment %}
                            <p>{{ customer.comment }}</p>
                        {% else %}
                            <p>Не указано</p>
                        {% endif %}
                    </div>
                </div>
            </div>
        </div>
        <div class='modal_modal' id='del_{{ customer.id }}'>
            <div class='content'>
                <h1>Подтвердите действие</h1>
                <a class='btn btn-danger' data-modal_modal="#tender-delete" href="{% url 'customers:customer_delete' customer.id %}">Подвердить</a>
                <a class='close-modal_modal btn btn-dark' data-modal_modal="#del_{{ product.id }}" href="#">Отмена</a>
            </div>
        </div>
{% endblock %}

sagsystem/customers/templates/customers/customer_edit.html
{% extends 'wrapper.html' %}
{% load static %}
{% block title %}{{ customer.name }} - изменить{% endblock %}
{% block content %}
    <div class="row incidents">
        {% include 'blocks/logo.html' %}
        {% include 'blocks/title.html' %}
        {% include 'blocks/profile.html' %}
        {% include 'customers/blocks/menu.html' %}
        <div class="col-xl-9 block__wrapper tenders-new">
            <div class="block tenders-new__wrapper">
                <h1 class="tenders-new__title">{{ customer.name }} - изменить</h1>
                <form method="POST">
                    {% csrf_token %}
                    <label for="name">ФИО</label>
                    <input required type="text" class="tenders-new__input form-control" name="name" id="name" value="{{ customer.name }}">
                    <label for="phone">Номер телефона</label>
                    <input type="number" class="tenders-new__input form-control" name="phone" id="phone" value="{{ customer.phone }}">
                    <label for="date_of_birth">Дата рождения</label>
                    <input type="date" id="date_of_birth" name="date_of_birth" class="tenders-new__input form-control" value="{{ customer.date_of_birth|date:'Y-m-d'}}">
                    <div class="tenders-new__select input-group mb-3">
                        <div class="input-group-prepend">
                            <label class="input-group-text" for="sex">Пол</label>
                        </div>
                        <select class="tenders-new__input custom-select" name="sex" id="sex">
                                {% if customer.sex == 'Ж' %}
                                    <option value="М">М</option>
                                    <option value="Ж" selected>Ж</option>
                                {% else %}
                                    <option value="М" selected>М</option>
                                    <option value="Ж">Ж</option>
                                {% endif %}
                        </select>
                    </div>
                    <label for="address">Адрес</label>
                    <input type="text" class="tenders-new__input form-control" name="address" id="address" value="{{ customer.address }}">
                    <label for="telegram">Telegram</label>
                    <input type="text" class="tenders-new__input form-control" name="telegram" id="telegram" value="{{ customer.telegram }}">
                    <label for="facebook">Facebook</label>
                    <input type="text" class="tenders-new__input form-control" name="facebook" id="facebook" value="{{ customer.facebook }}">
                    <label for="instagram">Instagram</label>
                    <input type="text" class="tenders-new__input form-control" name="instagram" id="instagram" value="{{ customer.instagram }}">
                    <label for="comment">Комментарий</label>
                    <textarea name="comment" id="comment" cols="30" rows="10" class=" form-control tenders-new__textarea">{{ customer.comment }}</textarea>
                    <input type="submit" class="tenders-new__button btn btn-success" value="Сохранить" id="add_product">
                    <a href="{% url 'customers:customer_list' %}" class="tenders-new__button btn btn-dark">Отмена</a>
                </form>
            </div>
        </div>
    </div>
{% endblock %}

sagsystem/customers/templates/customers/customer_export_ready.html
{% extends 'wrapper.html' %}
{% load static %}
{% block title %}Скачать базу{% endblock %}
{% block content %}
    <div class="row incidents">
        {% include 'blocks/logo.html' %}
        {% include 'blocks/title.html' %}
        {% include 'blocks/profile.html' %}
        {% include 'customers/blocks/menu.html' %}
        <div class="col-xl-9 block__wrapper tenders-new">
            <div class="block tenders-new__wrapper">
                <h1 class="tenders-dashboard__title">Скачать базу</h1>
                <h5>Ваша база готова, можете скачать ее.</h5>
                <a href="{% static 'temp/export.xlsx' %}" class="btn btn-success">Скачать</a>
                <a href="{% url 'customers:customer_list' %}" class="btn btn-primary">Назад на главную</a>
            </div>
        </div>
{% endblock %}

sagsystem/customers/templates/customers/customer_list.html
{% extends 'wrapper.html' %}
{% load static %}
{% block title %}База клиентов - Sagsystem{% endblock %}
{% block content %}
    <div class="row incidents">
        {% include 'blocks/logo.html' %}
        {% include 'blocks/title.html' %}
        {% include 'blocks/profile.html' %}
        {% include 'customers/blocks/menu.html' %}
        <div class="col-xl-9 block__wrapper tenders-dashboard">
            <div class="block tenders-dashboard__wrapper">
                <h1 class="tenders-dashboard__title">Все клиенты: {{ customers.count }}</h1>
                <a href="{% url 'customers:customer_add' %}" class="btn btn-success tenders-dashboard__new-tender">Добавить</a>
                <table class="table table-striped" id="datatable">
                    <thead>
                    <tr>
                        <th scope="col">ФИО</th>
                        <th scope="col">Номер телефона</th>
                        <th scope="col">Дата рождения</th>
                        <th scope="col">Пол</th>
                        <th scope="col" class="tenders-dashboard__buttoncell">Изменить</th>
                        {% if 5 in groups %}
                        {% else %}
                            <th scope="col" class="tenders-dashboard__buttoncell">Удалить</th>
                        {% endif %}
                    </tr>
                    </thead>
                    <tbody>
                    {% if customers %}
                        {% for customer in customers %}
                            <tr>
                                <td class="my-incidents__cell">{% if customer.name %}<a href="{% url 'customers:customer_detail' customer.id %}">{{ customer.name }}</a>{% else %}<a href="{% url 'customers:customer_detail' customer.id %}">Без имени</a>{% endif %}</td>
                                <td class="my-incidents__cell">{{ customer.phone }}</td>
                                <td class="my-incidents__cell">{{ customer.date_of_birth }}</td>
                                <td class="my-incidents__cell">{{ customer.sex }}</td>
                                <td><a href="{% url 'customers:customer_edit' customer.id %}" class="btn btn-warning">Изменить</a></td>
                                {% if 5 in groups %}
                                {% else %}
                                    <td><a href="#" class="open-modal_modal btn btn-danger" data-modal_modal="#del_{{ customer.id }}">Удалить</a></td>
                                {% endif %}
                            </tr>
                        {% endfor %}
                    {% else %}
                        <tr>
                            <td colspan="5">Нет данных</td>
                        </tr>
                    {% endif %}
                    </tbody>
                </table>
            </div>
        </div>
        {% for customer in customers %}
            <div class='modal_modal' id='del_{{ customer.id }}'>
                <div class='content'>
                    <h1>Подтвердите действие</h1>
                    <a class='btn btn-danger' href="{% url 'customers:customer_delete' customer.id %}">Подвердить</a>
                    <a class='close-modal_modal btn btn-dark' data-modal_modal="#del_{{ customer.id }}" href="#">Отмена</a>
                </div>
            </div>
        {% endfor %}
    </div>
{% endblock %}